# Generated by Django 6.0.3 on 2026-04-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guitarra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseprivada',
            name='enlace_jitsi',
            field=models.URLField(blank=True, help_text='Enlace a la videollamada Jitsi', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pais',
            field=models.CharField(blank=True, choices=[('España', 'España'), ('Argentina', 'Argentina'), ('México', 'México'), ('Estados Unidos', 'Estados Unidos'), ('Colombia', 'Colombia'), ('Chile', 'Chile'), ('Perú', 'Perú'), ('Venezuela', 'Venezuela'), ('Uruguay', 'Uruguay'), ('Paraguay', 'Paraguay'), ('Brasil', 'Brasil'), ('Francia', 'Francia'), ('Italia', 'Italia'), ('Alemania', 'Alemania'), ('Reino Unido', 'Reino Unido'), ('Portugal', 'Portugal'), ('Rusia', 'Rusia'), ('China', 'China'), ('Japón', 'Japón'), ('India', 'India'), ('Canadá', 'Canadá'), ('Australia', 'Australia'), ('Marruecos', 'Marruecos'), ('Egipto', 'Egipto'), ('Sudáfrica', 'Sudáfrica'), ('Nigeria', 'Nigeria'), ('Turquía', 'Turquía'), ('Grecia', 'Grecia'), ('Suecia', 'Suecia'), ('Noruega', 'Noruega'), ('Finlandia', 'Finlandia'), ('Dinamarca', 'Dinamarca'), ('Polonia', 'Polonia'), ('Países Bajos', 'Países Bajos'), ('Bélgica', 'Bélgica'), ('Suiza', 'Suiza'), ('Austria', 'Austria'), ('Hungría', 'Hungría'), ('Rumanía', 'Rumanía'), ('Bulgaria', 'Bulgaria'), ('Serbia', 'Serbia'), ('Croacia', 'Croacia'), ('Eslovenia', 'Eslovenia'), ('Eslovaquia', 'Eslovaquia'), ('República Checa', 'República Checa'), ('Ucrania', 'Ucrania'), ('Bielorrusia', 'Bielorrusia'), ('Lituania', 'Lituania'), ('Letonia', 'Letonia'), ('Estonia', 'Estonia'), ('Irlanda', 'Irlanda'), ('Islandia', 'Islandia'), ('Luxemburgo', 'Luxemburgo'), ('Mónaco', 'Mónaco'), ('Andorra', 'Andorra'), ('San Marino', 'San Marino'), ('Malta', 'Malta'), ('Chipre', 'Chipre'), ('Otros', 'Otros')], max_length=100),
        ),
    ]
