# Generated by Django 6.0.3 on 2026-03-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guitarra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claseprivada',
            name='palo_flamenco',
            field=models.CharField(choices=[('Bulería', 'Bulería'), ('Alegrías', 'Alegrías'), ('Tangos', 'Tangos'), ('Soleá', 'Soleá'), ('Tanguillo', 'Tanguillo'), ('Fandango', 'Fandango'), ('Rumba', 'Rumba'), ('Canción Famosa', 'Canción Famosa')], max_length=100),
        ),
    ]
