# Generated by Django 6.0.3 on 2026-04-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guitarra', '0002_claseprivada_enlace_jitsi_alter_profile_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claseprivada',
            name='enlace_jitsi',
        ),
    ]
