# Generated by Django 6.0.3 on 2026-04-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guitarra', '0003_remove_claseprivada_enlace_jitsi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
