# Generated by Django 6.0.3 on 2026-05-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guitarra', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitarra',
            name='tipo',
        ),
        migrations.AddField(
            model_name='guitarra',
            name='color',
            field=models.CharField(choices=[('Clara', 'Clara'), ('Oscura', 'Oscura'), ('Roja', 'Roja'), ('Naranja', 'Naranja')], default='Clara', max_length=20),
        ),
    ]
